### ISSUE TITLE
Translatable ?

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [DarkMooNight/ToDark#2]
Is the app translatable and when, where are the strings to translate ?
Thanks in advance.

**Comment by Leonavichus** [comment]
I don't quite understand you. The application is translated automatically, determining the system language of the phone. The translation is located in the file ToDark/lib/l10n/translation.dart.

**Comment by Terkyz** [comment]
> I don't quite understand you. The application is translated automatically, determining the system language of the phone. The translation is located in the file **ToDark/lib/l10n/translation.dart**.

I think something is wrong with the automatic translation, on my Android 11 device with the system language in [spanish](https://i.imgur.com/G1TE88l.jpg) the app is in [english](https://i.imgur.com/GiPbNtN.jpg) in some parts and in [russian](https://imgur.com/c8revqc.jpg) in others, and ironically there is no spanish anywhere

**Comment by Leonavichus** [comment]
Unfortunately, there is no Spanish yet. There are English and Russian. And I probably didn't notice the mistake, thanks for telling me.

> > I don't quite understand you. The application is translated automatically, determining the system language of the phone. The translation is located in the file **ToDark/lib/l10n/translation.dart**.
> 
> I think something is wrong with the automatic translation, on my Android 11 device with the system language in [spanish](https://i.imgur.com/G1TE88l.jpg) the app is in [english](https://i.imgur.com/GiPbNtN.jpg) in some parts and in [russian](https://imgur.com/c8revqc.jpg) in others, and ironically there is no spanish anywhere

Unfortunately, there is no Spanish yet. There are English and Russian. And I probably didn't notice the mistake, thanks for telling me.
