### ISSUE TITLE
Добавить виджеты

### ISSUE THREAD

**Issue by f1refa11** [DarkMooNight/ToDark#24]
Их дизайн я ещё не могу представить на данный момент, но как только я буду за компом, нарисую чё-нибудь в Inkscape :)

**Comment by Leonavichus** [comment]
Я сейчас переписываю данные приложение, так что наверное не скоро виджеты будут. Да и такая задача уже есть #8.

**Comment by f1refa11** [comment]
> Да и такая задача уже есть #8.
Прошу прощения, не заметил.
