### ISSUE TITLE
Кнопка Пожертвований :)

### ISSUE THREAD

**Issue by f1refa11** [DarkMooNight/ToDark#26]
был бы рад, если бы вы добавили кнопку-ссылку на донат - как минимум на DonationAlerts. Просто мне очень нравится данное приложение т.к. очень хорошо проработан дизайн и хотелось бы либо помочь в разработке либо помочь материально 👍

**Comment by Leonavichus** [comment]
Постараюсь сделать. Также я сейчас переделываю дизайн, надеюсь она вам тоже понравится.

**Comment by Leonavichus** [comment]
Добавил ссылку на донат в описании проекта.

**Comment by Leonavichus** [comment]
В следующей версии добавлю и в приложение.
