### ISSUE TITLE
Internet permission

### ISSUE THREAD

**Issue by IzzySoft** [darkmoonight/ToDark#3]
Just wondering what the `INTERNET` permission is requested for by your app. Does it offer some synchronisation features – or is it something else? It's declared (as only permission) in [`AndroidManifext.xml`](https://github.com/DarkMooNight/ToDark/blob/main/android/app/src/main/AndroidManifest.xml#L4). Maybe it wasn't even intended and is a left-over from some testing?

**Comment by Leonavichus** [comment]
This was done as a result of testing, I forgot to remove it.

**Comment by IzzySoft** [comment]
Ah, so my guess was right :rofl: Thanks for your fast answer! I guess you will remove it then with the next release?

**Comment by Leonavichus** [comment]
Yes, it won't be in the next release.

**Comment by IzzySoft** [comment]
Thanks!

**Comment by vish9812** [comment]
The Neo Store still shows that the app needs internet permission.

**Comment by Uranusek** [comment]
I noticed that the app has the "view network connections" permission. Why? 🤔

**Comment by Leonavichus** [comment]
> I noticed that the app has the "view network connections" permission. Why? 🤔 

This is most likely due to one of the libraries used in the application. This issue will be resolved in the next update.
