### ISSUE TITLE
Dynamic theme automatically turns off after closing the app

### ISSUE THREAD

**Issue by Embassy4016** [DarkMooNight/ToDark#37]
I am on grapheneos Android 14. Dynamic theme on todark automatically turns off after closing the app.

**Comment by Leonavichus** [comment]
This is strange. I will download an emulator from grapheneos and try to find out the reason.

**Comment by Embassy4016** [comment]
![Screenshot_20231017-230124](https://github.com/DarkMooNight/ToDark/assets/140226326/3efd0647-6d3a-469a-91ef-86e6c8af5f7b)

**Comment by Leonavichus** [comment]
Update the app to version 1.4.5, there is no such error in this version.

**Comment by Embassy4016** [comment]
Okay... The version 1.4.5 seems to have solved it after updating.
