### ISSUE TITLE
the way you use git horible (please take a git course)

### ISSUE THREAD

**Issue by nakibrayan3** [darkmoonight/ToDark#38]
@Leonavichus  the way you use git is horrible. the commit log is useless and the commit messages don't mean a thing.

and you don't get any of the benefits of using git this way.

this is a really bad way to maintain an opensource project. GitHub is a collaboration platform  but the way you use git makes it impossible to collaborate with you.

please take a git course, there is a lot of free courses in the internet, just pick a good one and follow it.

and organize the project more:

- add issues template
- create `CONTRIBUTING.md` to show other developers how to contributes and translator how to translate the app.
- create Pull Requests don't push changes directly to the main branch
- create and IRC or Matrix chat for contributes to talk without create an issue

i can help you with most of these things (other than the commit messages).

**Comment by Leonavichus** [comment]
> @Leonavichus the way you use git is horrible. the commit log is useless and the commit messages don't mean a thing.
> 
> and you don't get any of the benefits of using git this way.
> 
> this is a really bad way to maintain an opensource project. GitHub is a collaboration platform but the way you use git makes it impossible to collaborate with you.
> 
> please take a git course, there is a lot of free courses in the internet, just pick a good one and follow it.

For me, github is first and foremost a code repository. I never expected to work with people on my projects. Since I didn't anticipate this much interest in them. As for naming the commit messages, yet, here I am among them without giving any strong meaning. I will endeavour to correct myself here.

> and organize the project more:
> 
>     * add issues template
> 
>     * create `CONTRIBUTING.md` to show other developers how to contributes and translator how to translate the app.
> 
>     * create Pull Requests don't push changes directly to the main branch
> 
>     * create and IRC or Matrix chat for contributes to talk without create an issue

I'll try to do that, but probably not all of them.
