### ISSUE TITLE
Add italian translation

### ISSUE THREAD

**Issue by CavaleriOmar** [darkmoonight/ToDark#50]
Would it be possible to add Italian localization? Or, what could be done to help make it happen?

**Comment by f1refa11** [comment]
For now, the app doesn't have some sort of translation app like Weblate or Crowdin, but as far as i know, you can submit a new localization by:
1. adding it-it.dart language file(based on [en_us.dart](https://github.com/darkmoonight/ToDark/blob/556267ce8a03728c9ce057e6d36193570316febc/lib/translation/en_us.dart)) with translated messages(**don't forget to change the class name on line 1 to ItIt**)
2. and then adding a new localization in [translation.dart](https://github.com/darkmoonight/ToDark/blob/556267ce8a03728c9ce057e6d36193570316febc/lib/translation/translation.dart):
```dart
import 'package:get/get.dart';
import 'package:todark/translation/ar_ar.dart';
import 'package:todark/translation/de_de.dart';
import 'package:todark/translation/en_us.dart';
import 'package:todark/translation/es_es.dart';
import 'package:todark/translation/fa_ir.dart';
import 'package:todark/translation/fr_fr.dart';
import 'package:todark/translation/ru_ru.dart';
import 'package:todark/translation/zh_cn.dart';
import 'package:todark/translation/zh_tw.dart';
import 'package:todark/translation/it_it.dart'; // add this line

class Translation extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'ru_RU': RuRu().messages,
        'en_US': EnUs().messages,
        'zh_CN': ZhCN().messages,
        'zh_TW': ZhTw().messages,
        'fa_IR': FaIr().messages,
        'ar_AR': ArAr().messages,
        'es_ES': EsEs().messages,
        'fr_FR': FrFr().messages,
        'de_DE': DeDe().messages,
		'it_IT': ItIt().messages // add this line
      };
}
