### ISSUE TITLE
Use a translation app(like Weblate or Crowdin)

### ISSUE THREAD

**Issue by f1refa11** [darkmoonight/ToDark#51]
By using a translation app other contributors would be able to translate the app to different languages **without the knowledge of programming**.

AFAIK, both Weblate or Crowdin give additional Pro features for open-source projects, so i think it all depends on what service will approve this app.

**Comment by f1refa11** [comment]
why was it marked as "not planned"??

**Comment by Leonavichus** [comment]
I don't really want to bother with the setup in these services
