### ISSUE TITLE
Question on permission: READ_EXTERNAL_STORAGE

### ISSUE THREAD

**Issue by IzzySoft** [darkmoonight/ToDark#52]
My scanner just got a few additional checks implemented, and on today's update of your app reported:

    ! repo/com.yoshi.todark_2037.apk declares risky permission(s): android.permission.READ_EXTERNAL_STORAGE

Could you please clarify what this permission is needed for? One needs Android 6 or higher to use the app, so I'd assume you'd use SAF (Storage Access Framework) for file system access. Are there any places outside its reach ToDark needs to access?

Thanks in advance for clarification!

**Comment by Leonavichus** [comment]
I used it to record backups.
```
SAF (Storage Access Framework)
```
I didn't know about it, thanks for telling me. I will try to remove the extension in the near future.

**Comment by IzzySoft** [comment]
There are some difficulties with storage access between Android 5 and 9, even with SAF (storage permissions are quite confusing there between Android versions). But if it's just about a single location to store backups, SAF should do: first time the user has to pick a location (via the file picker) to grant the app access to, and then the app could use that to read/write files. Some locations are not available this way (e.g. media directories or the Downloads directory) – but most places on external storage (except its root directory itself) can be picked from AFAIK.

**Comment by IzzySoft** [comment]
Just wondering: The issue is closed, but the permission is still requested:

```
! repo/com.yoshi.todark_2041.apk declares sensitive permission(s): android.permission.READ_EXTERNAL_STORAGE
! repo/com.yoshi.todark_2041.apk contains signature block blobs: 0x504b4453 (DEPENDENCY_INFO_BLOCK; GOOGLE)
```

Hope the issue being closed does not mean you forgot about it, @Leonavichus? As for `DEPENDENCY_INFO_BLOCK`, this is easy to get rid of:

```gradle
android {
    dependenciesInfo {
        // Disables dependency metadata when building APKs.
        includeInApk = false
        // Disables dependency metadata when building Android App Bundles.
        includeInBundle = false
    }
}
```

For some background: that BLOB is supposed to be just a binary representation of your app's dependency tree. But as it's encrypted with a public key belonging to Google, only Google can read it – and nobody else can even verify what it really contains.
