### ISSUE TITLE
[Feature Request] Toggle to switch between 24h and 12h time formats

### ISSUE THREAD

**Issue by SunDevil311** [darkmoonight/ToDark#53]
**Is your feature request related to a problem? Please describe.**
Recently started using ToDark and it seems an incredibly well-designed, good looking app. However, I'm a little less than enthusiastic about there not being a way to switch to 12h time (as far as I can tell). While I have enough experience with 24h time to muddle through, it would really be nice to have the option for 12h time.

**Describe the solution you'd like**
A toggle in Settings to switch between 12h and 24h time seems the easiest solution (not sure how difficult that is to implement). Given that 12h is what those of us in the States are used to, such a feature would potentially result in broader appeal for ToDark.

**Describe alternatives you've considered**
Continue to use 24h time, I suppose? Anything I can't do in my head, I have a time zone app for that will convert 24h to the more familiar 12h value. Already have a ToDo app I'm pretty happy with, but this project seems to have a lot of potential.

**Additional context**
I think the issue is pretty self-explanatory. Lmk if there are any questions!

~ SunDevil

**Comment by Leonavichus** [comment]
I will try to implement this this week.

**Comment by SunDevil311** [comment]
@Leonavichus ty!
