### ISSUE TITLE
Application have no title in the task switcher

### ISSUE THREAD

**Issue by Porkepix** [DarkMooNight/ToDark#57]
**Describe the bug**
When displaying the task switcher with ToDark opened, it doesn't present a title as it should and every other application does.

**To Reproduce**
1. Show the task switcher with ToDark opened.

**Expected behavior**
A title should be there

**Screenshots**
<details>

![Screenshot_20240307-202349](https://github.com/darkmoonight/ToDark/assets/709500/6db060f2-4ccc-48df-9dc9-10bff2cdf023)

</details>

**Smartphone (please complete the following information):**
 - Device: Xperia XZ
 - OS: Android Oreo (8.0)
 - Version: 1.4.9

**Additional context**

Note also that the preview doesn't show anything in the task switcher, but that might be a privacy choice or a rendering issue from the phone, so I'm not sure about opening an issue on that one.

**Comment by Leonavichus** [comment]
Can you see if everything is working fine now?
