### ISSUE TITLE
ToDark still usable when phone is locked

### ISSUE THREAD

**Issue by citroniais** [DarkMooNight/ToDark#6]
I have a Fairphone 4 with iodéOS 4.1 (Android 13).
When I lock the phone, the app is still accessible and fully usable...
Is this a known problem?

**Comment by Leonavichus** [comment]
Hello, I did not know about this problem, I will fix it soon.

**Comment by citroniais** [comment]
Thanks !

**Comment by Leonavichus** [comment]
The problem has been fixed.
