### ISSUE TITLE
Please!!! Take away those ugly, bulky drawings. In the amoled theme they especially stand out by their ugliness and bulky, they make me want to take my eyes off them and GO TO ANOTHER APPLICATION as I did.

### ISSUE THREAD

**Issue by Wjxfi** [darkmoonight/ToDark#62]
Please!!! Take away those ugly, bulky drawings. In the amoled theme they especially stand out by their ugliness and bulky, they make me want to take my eyes off them and GO TO ANOTHER APPLICATION as I did.
![f86bbfd7-b6c0-4409-8b65-108469ccaeb2.jpg](https://github.com/darkmoonight/ToDark/assets/113500363/2d431a42-2339-4a3e-ab1f-c104a98c77c0)

Please…

**Comment by f1refa11** [comment]
do you have at least 1 suggestion for what should be shown instead of this image?
