### ISSUE TITLE
[Feature Request] Set priority in tasks

### ISSUE THREAD

**Issue by niklas-fischer** [darkmoonight/ToDark#66]
Hello there! I really like your app, it has nearly everything someone could need to plan and do their daily tasks!

One thing I'm missing and that's preventing me from changing my To-Do app:
To specify the priority of a task, maybe like high, middle, low or anything like that. 

That'd help to see what is necessary to do and is urgent.

What do you think about that? 

Many thanks for your current work!

**Comment by Leonavichus** [comment]
Hi! 
I'll put your suggestion on the to-do list.
